QodeFarm/cnl-backend

- apps/company/models.py
- apps/company/serializers.py
updated country_id and state_id and added num_employees in companies.
> updated Company module

- apps/customer/models.py
- apps/customer/serializers.py
- config/settings.py
- config/urls.py
- config/views.py
added state and country ids in customer addresses table.
> updated customer addresses table.

- apps/company/models.py
- apps/company/serializers.py
- apps/company/urls.py
- apps/company/views.py
- apps/masters/models.py
- utils_methods.py
Updated null value related things and did a minor change in encryption(utils_methods).
> 80 updating company module

- apps/products/filters.py
- config/settings.py
updated as per requirement(changed products.filters.py)
> updated as per requirement

- apps/products/models.py
- apps/products/serializers.py
- apps/sales/filters.py
- apps/sales/models.py
- apps/sales/serializers.py
- database/cnl.sql
Replaced group_id with product_group_id
> replaced group_id with product_group_id

- apps/customer/serializers.py
- apps/customer/views.py
added summary to customer module.
> updated summary to customer

- apps/masters/views.py
- apps/products/serializers.py
- apps/products/views.py
> 157 product summary

- apps/customer/serializers.py
- apps/customer/views.py
> updated customer summary

- apps/customer/models.py
- apps/sales/serializers.py
- apps/sales/views.py
- config/utils_methods.py
Added PUT method to sales/views.py
Deleted old - update_multi_instance  - function
added New - update_multi_instance - function
> 168 sales module implement data sync across apis for all crud operations

- apps/customer/urls.py
- apps/customer/views.py
updated customer-order with required JSON format.
> updated customer-order

- apps/purchase/views.py
- requirements.txt
> 163 crud operations on purchase module

- apps/customer/views.py
- config/utils_methods.py
Updated CRUD Operations in customer module.
> Updated new changes in customer module

- apps/customer/urls.py
- apps/customer/views.py
added summary logic to customers module.
> updated summary in customers module.

- database/cnl.sql
> lead management db structures

- database/cnl.sql
> hrms related tables

- database/cnl.sql
> asset related db tables

- apps/assets/models.py
- apps/assets/serializers.py
- apps/tasks/urls.py
- apps/tasks/views.py
- database/cnl.sql
created task view and added unit_options_id in assets
> 230 curd operations on task module

- apps/leads/views.py
> Hrms leads apiview crud operations

- apps/leads/views.py
now in create mode : 
-----------------------
default lead status is - "open"   (can be changed in PUTmethod)
update method :
------------------
If 'sales_rep_id' is changed then history is updates with end date for previous 'sales_rep_id' and new history instance will be 
created for updated 'sales_rep_id'.
and same 'sales_rep_id' can be ended by providing end date in hostory_data.
if the same 'sales_rep_id' wants to continue , then new history instance will be created for 'sales_rep_id'.
> updated create and post method

- database/cnl.sql
> Leads updated download code updated

- apps/sales/models.py
- database/cnl.sql
added new logic to sale invoice and sale returns.
> updated sales invoice and sales returns in sales.

- apps/products/serializers.py
- apps/sales/serializers.py
updated order_status_id in sales
> updated order_status in sales.

- apps/products/views.py
> updated picture field

- apps/products/views.py
> updated views.py file in products

- apps/customer/models.py
- apps/customer/serializers.py
- apps/customer/views.py
- apps/vendor/views.py
updated picture field in vendors and customers.
> updated vendor and customer picture field.

- apps/customer/views.py
- apps/products/views.py
- apps/vendor/views.py
updated picture field with put method.
> updated put method for picture

- apps/users/models.py
- apps/users/serializers.py
- apps/users/url.py
- apps/users/views.py
added code for Get, Get all, update, delete User.
Also added 2 column in model, serializer.
added try..except block for role_permissions while returning token at time of login.
> added code for Get, Get all, update, delete User

- apps/vendor/models.py
updated picture field in vendors.
> updated vendors picture field.

- apps/users/models.py
- apps/users/serializers.py
- apps/users/url.py
- apps/users/views.py
added code for Get, Get all, update, delete User.
Also added 2 column in model, serializer.
added try..except block for role_permissions while returning token at time of login.
8-11
removed company_id column, spaces, user_list url and view, added comments
Added last_login code(Now this will add current dateTime in last_login column)
> 296 user update issue

- apps/users/models.py
- apps/users/serializers.py
- apps/users/views.py
added code for profile pic upload so now we can upload profile pic while creating account and update account .
> added code for profile pic upload

- apps/company/serializers.py
- apps/purchase/models.py
- apps/sales/models.py
updated order_status and logo fields
> updated order_status field and company logo field.

- apps/users/views.py
Added custom logic for delete user in users.view
> added custom logic for delete user

- apps/inventory/serializers.py
- apps/products/serializers.py
- apps/products/views.py
updated serializers and added delete method. 
made changes in serializer methods in product Serializer.
> added changes in products serializers and added delete method

- apps/products/models.py
- apps/products/serializers.py
- apps/products/views.py
> Update inventory view list

- apps/sales/filters.py
added customer_id in filters.py file
> added customer_id in sale invoice filters.py file

- apps/sales/filters.py
added order_status_id in filters.py file
> updated order_status_id field in sales module.

- apps/sales/filters.py
- apps/sales/serializers.py
- apps/sales/views.py
added filter for sale_order_items thing.
> updated filter in SaleOrderItemsFilterclass

- apps/masters/models.py
- apps/masters/serializers.py
- apps/masters/urls.py
- apps/masters/views.py
- apps/sales/models.py
- apps/sales/serializers.py
- config/utils_variables.py
- database/cnl.sql
added return options table & return option relation in sale return table
> added return_options table

- apps/sales/models.py
- apps/sales/serializers.py
Added workflow_id logic in sale_order.
> added logic for workflow_id

- apps/sales/views.py
updated a correction in views.py file.
> updated views.py file in backend.

- apps/masters/views.py
- apps/sales/models.py
- apps/sales/views.py
- database/cnl.sql
updated required changes in backend.
> updated sales module.

- apps/sales/models.py
- apps/sales/serializers.py
- apps/sales/urls.py
- apps/sales/views.py
- database/cnl.sql
added required logics for sale credit notes table
> updated sale credit notes in sales app.

- apps/finance/urls.py
- apps/finance/views.py
removed extra invoice endpoint.
> removed invoice end point

- apps/sales/urls.py
- apps/sales/views.py
added patch method to sale credit note APIView
> updated sale credit note views

- apps/sales/models.py
added default status_name in sales for credit & debit notes
> added default status_name in sales for credit & debit notes

- apps/sales/models.py
updated order_status_id in sales app
> updated order_status_id in sales.

- apps/sales/models.py
- apps/sales/serializers.py
- database/cnl.sql
added sale_return_id in sales app.
> updated sale_return_id in sales app.

- apps/sales/views.py
updated put method for sales app
> updated put method in sales app

- apps/purchase/filters.py
- apps/sales/filters.py
updated sales and purchase filters
> 345 pagination sort search filters

- apps/sales/models.py
udpated workflow_id filed in models.py file
> updated workflow_id in sales models.py file.

- apps/sales/models.py
> updated shipping tracking no.

- apps/sales/models.py
- apps/sales/serializers.py
- database/cnl.sql
sale_estimate field added in sale_order table.
> added sale_estimate field in sale_order table.

- apps/hrms/filters.py
- apps/hrms/views.py
I have made some code changes in views.py and filters.py files.
> updated latest changes

- apps/production/models.py
- apps/production/views.py
- config/utils_variables.py
- database/cnl.sql
Added exception handling, and sync qty is set to True, after update.
> 442 completed qty column removal sync option enhancement

- apps/products/serializers.py
- config/settings.py
updated ModProductSerializers in product module.
> updated serializers.py file in products.

- apps/production/models.py
- apps/production/serializers.py
- apps/production/views.py
- apps/products/serializers.py
- config/settings.py
- config/utils_methods.py
**Stock Journal is completed,**
**Additional updates for workorder:**
now empty rows (workers, machines, etc.) will not affect when submitting the form from Frontend side.
> 450 stock journal

- apps/inventory/urls.py
updated inventory urls.py file.
> updated inventory urls.py file.

- apps/sales/models.py
updated order_status field in sales module.
> updated order_status field in sales module.

- apps/customfields/filters.py
- apps/customfields/views.py
- database/cnl.sql
added filters for custom field options.
> added filters for custom field options.

- apps/customer/views.py
- apps/customfields/models.py
- apps/customfields/serializers.py
- apps/purchase/serializers.py
- apps/vendor/views.py
added custom fields logic for vendors in backend.
> added custom fields logic for vendors in backend.

- config/settings.py
disabled cors in settings.py file.
> disabled cors in settings.py file.

- config/settings.py
> cors enabled.

- config/settings.py
added new server name in settings.py file.
> added new server name in settings.py file.

- apps/sales/views.py
> timedelta error fixed

- config/settings.py
> updated settings.py file

- config/asgi.py
- config/settings.py
- config/wsgi.py
- middleware/middleware.py
files updated with recent changes in server.
> files updated with recent changes in server.

- apps/users/views.py
Added pop-up message for user enter incorrect login credentials.
> Login issues show msgs

- apps/customer/serializers.py
- apps/customer/views.py
- apps/vendor/serializers.py
Customers and vendors issues resolved
> Document format

- apps/sales/models.py
- config/settings.py
added workflow_disable logic and also fixed UI issue in backend.
> added workflow_disable logic and also ui backend.

- apps/customer/views.py
- apps/products/serializers.py
- apps/vendor/views.py
> backend test issues

- apps/customer/models.py
- apps/customer/views.py
- apps/sales/views.py
- config/utils_methods.py
added logic for customer details storing.
> added logic for customer details storing.

- apps/finance/filters.py
- apps/finance/models.py
- apps/finance/serializers.py
- apps/finance/urls.py
- apps/finance/views.py
- config/utils_variables.py
Implemented a complete expense tracking system and created views, filters, models classes and serializers.
> Add Expense Tracker System Backend

- database/cnl.sql
Implemented a complete expense tracking system and created views, filters, models classes and serializers.
> added expense_categories and expense_items in local DB file

- apps/customer/views.py
- apps/masters/views.py
- apps/sales/models.py
- apps/sales/signals.py
- apps/sales/views.py
- apps/users/models.py
- config/utils_methods.py
Added code logic for Other and signals in Backend
> Customer contact

- apps/sales/models.py
uncommented use_workflow field
> uncommented use_workflow field

- apps/customfields/views.py
- apps/production/views.py
- apps/sales/filters.py
- apps/sales/serializers.py
- apps/sales/views.py
- config/utils_methods.py
added logic for sales receipt and fixed issues in sales modules.
> Pramod testing be

- apps/customer/views.py
removed customer mstcnl logic in views.py
> removed customer mstcnl logic in views.py

- apps/masters/views.py
- apps/purchase/models.py
- apps/sales/models.py
- apps/sales/views.py
- config/utils_methods.py
added logic for order_no all sales and purchase whole module and products.
> Sale child calc be

- apps/masters/template/sales/sales_doc.py
- apps/masters/template/table_defination.py
- apps/masters/views.py
- apps/sales/views.py
- config/utils_methods.py
> added logic for sale returns.

- apps/masters/views.py
added code for return option exclude sale order
> ADDED code for return option exclude sale order

- apps/customer/urls.py
- apps/customer/views.py
- config/utils_methods.py
Import Script add for Customer. created CustomerTemplateAPIView and CustomerExcelUploadAPIView
> Import Script add for Customer. created CustomerTemplateAPIView and CustomerExcelUploadAPIView

- apps/production/models.py
in model classe i have chnages few fileds stage_name,machine_id, null=true
> in model classe i have chnages few fileds stage_name,machine_id, null=true

- apps/products/filters.py
- apps/products/views.py
Added Filters for inventory and products Type,  group, category,and warehouse
> Added filters for inventory and prodcuts

- apps/customer/views.py
- apps/finance/models.py
- apps/finance/views.py
- apps/hrms/models.py
- apps/hrms/views.py
- apps/production/models.py
- apps/production/views.py
- apps/purchase/models.py
- apps/purchase/views.py
- apps/sales/models.py
- apps/sales/views.py
- apps/tasks/models.py
- apps/tasks/views.py
- apps/vendor/views.py
Added logic for the safe deletion, workflow, sales changes.
> Sale workflow new bc

- apps/sales/serializers.py
- apps/sales/views.py
- apps/users/views.py
added paginations and summary fixes.
> added paginations and summary fixes.

- apps/sales/filters.py
- apps/sales/views.py
> global search fixed.

- apps/users/views.py
> changed super users subdomain
